events {}

http {

    log_format cat9
        '$time_iso8601 '
        'deployment=$deployment '
        'status=$status '
        'upstream_time=$upstream_response_time '
        'request_time=$request_time '
        'request="$request"';

    log_format cat9_shadow
        '$time_iso8601 '
        'shadow=1 '
        'status=$status '
        'upstream_time=$upstream_response_time '
        'request="$request"';

    access_log /var/log/nginx/cat9_access.log cat9;

    upstream stable {
        server host.docker.internal:8101;
    }

    upstream canary {
        server host.docker.internal:8102;
    }

    upstream shadow {
        server host.docker.internal:8102;
    }

    # CAT9_TRAFFIC_SPLIT_START
    split_clients $request_id $deployment {
        90% stable;
        * canary;
    }
    # CAT9_TRAFFIC_SPLIT_END

    server {
        listen 8080;

        location /healthz {
            proxy_pass http://stable;
        }

        location /predict {

            # Primary request.
            proxy_pass http://$deployment;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            add_header X-Canary-Deployment $deployment always;

            # Shadow copy.
            mirror /cat9_shadow;
            mirror_request_body on;
        }

        # Shadow requests are sent to v2.
        # Their response is discarded by nginx.
        location = /cat9_shadow {

            internal;

            proxy_pass http://shadow/predict;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-CAT9-Shadow true;

            access_log /var/log/nginx/cat9_shadow.log cat9_shadow;
        }
    }
}
